# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogon1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Obavijesti',
        ),
        migrations.RemoveField(
            model_name='telegram',
            name='user',
        ),
        migrations.DeleteModel(
            name='Telegram',
        ),
    ]
